#ifndef __RC_DEFINE_H__
#define __RC_DEFINE_H__

//WelcomeBack
#define REMOTECONFIG_FUNCTION_WELCOME_BACK_ENABLE "function_welcomeback_enable"
#define REMOTECONFIG_FUNCTION_WELCOME_BACK_DATA "function_welcomeback_data"

//Rating
#define REMOTECONFIG_FUNCTION_RATING_CONDITION "function_rating_condition"
#define REMOTECONFIG_FUNCTION_RATING_POPUP_ENABLE "function_rating_enable"
#define REMOTECONFIG_FUNCTION_RATING_IN_SETTING_ENABLE "function_rating_in_setting_enable"
#define REMOTECONFIG_FUNCTION_RATING_IN_APP_REVIEW_ENABLE "function_rating_in_app_review_enable"
#define REMOTECONFIG_FUNCTION_RATING_STATE_NEVER_SHOW "function_rating_state_never_show"

//Suggest Update
#define REMOTECONFIG_FUNCTION_SUGGEST_UPDATE_DATA "function_suggest_update_data"
#define REMOTECONFIG_FUNCTION_SUGGEST_UPDATE_ENABLE "function_suggest_update_enable"

//TimeBonus
#define REMOTECONFIG_FUNCTION_TIME_BONUS_ENABLE "function_time_bonus_enable"
#define REMOTECONFIG_FUNCTION_TIME_BONUS_MASTER_JSON "function_time_bonus_master_json"
#define REMOTECONFIG_FUNCTION_TIME_BONUS_VERSION_CODE "function_time_bonus_version_code"

//Mailbox
#define REMOTECONFIG_FUNCTION_MAILBOX_ENABLE "function_mailbox_enable"
#define REMOTECONFIG_FUNCTION_MAILBOX_DATA "function_mailbox_data"
#define REMOTECONFIG_FUNCTION_MAILBOX_CHECKED_LIMIT "function_mailbox_checked_limit"

//Share Game
#define REMOTECONFIG_FUNCTION_SHARE_GAME_LINK "function_share_game_json_data"


//Bot
#define REMOTECONFIG_FUNCTION_BOT_CONF_LEVEL "function_bot_conf_level"
#define REMOTECONFIG_FUNCTION_LIST_BOT_DATA "function_list_bot_data"

//News
#define REMOTECONFIG_FUNCTION_NEWS_POPUP_ENABLE "function_news_popup_enable"
#define REMOTECONFIG_FUNCTION_NEWS_POPUP_VERSION "function_news_popup_version"
#define REMOTECONFIG_FUNCTION_NEWS_POPUP_DATA "function_news_popup_data"

//Game center
#define REMOTECONFIG_FUNCTION_GAME_CENTER_POPUP_ENABLE "function_game_center_enable"
#define REMOTECONFIG_FUNCTION_GAME_CENTER_DATA "function_game_center_data"

//Decor
#define REMOTECONFIG_FUNCTION_EVENT_DECOR_ENABLE "function_event_decor_enable"
#define REMOTECONFIG_FUNCTION_EVENT_DECOR_JSON "function_event_decor_json"

// Ads
#define REMOTECONFIG_FUNCTION_ADS_SHOW_GET_REWARDS_ENABLE "function_ads_show_get_rewards_enable"
#define REMOTECONFIG_FUNCTION_ADS_SHOW_EXIT_GAME_ENABLE "function_ads_show_exit_game_enable"
#define REMOTECONFIG_FUNCTION_ADS_SHOW_INGAME_FREQUENCY "function_ads_show_ingame_frequency"
#define REMOTECONFIG_FUNCTION_SHOW_ADS "function_show_ads"
#define REMOTECONFIG_FUNCTION_ADS_SHOW_FORCE_APPLY_LEVEL "function_ads_show_force_apply_level"
#define REMOTECONFIG_FUNCTION_ADS_SHOW_FORCE_RATE "function_ads_show_force_rate"
#define REMOTECONFIG_FUNCTION_ADS_SHOW_FORCE_ENABLE "function_ads_show_force_enable"

//Notification
#define REMOTECONFIG_FUNCTION_LOCAL_NOTIFICATION_ENABLE "function_local_notification_enable"
#define REMOTECONFIG_FUNCTION_LOCAL_NOTIFICATION_DATA "function_local_notification"
#define REMOTECONFIG_FUNCTION_LOCAL_NOTIFICATION_CLEAN_CURRENT "function_local_notification_clean_current"


// Domain
#define REMOTECONFIG_FUNCTION_PRIVACY_POLICY_LINK "function_privacy_policy_link"

//Game services
#define REMOTECONFIG_FUNCTION_AUTO_SIGN_IN_GAME_SERVICE "function_auto_sign_in_game_service"
#define REMOTECONFIG_FUNCTION_GAME_SERVICE_ENABLE "function_game_service_enable"

//Text Localize
#define REMOTECONFIG_FUNCTION_LOCALIZE_TEXT "function_localize_text"

//Bet
#define REMOTECONFIG_FUNCTION_BET_DATA "function_bet_data"
#define REMOTECONFIG_FUNCTION_TARGET_SCORE_DATA "function_target_score_data"

//Developer
#define REMOTECONFIG_FUNCTION_DEVELOPER_NAME "function_developer_name"

//Money Range Name
#define REMOTECONFIG_FUNCTION_MONEY_RANGE_NAME "function_money_range_name"

#endif //__RC_DEFINE_H__
