#ifndef __INGAME_SERVER_OFFLINE_DEFINES_H__
#define __INGAME_SERVER_OFFLINE_DEFINES_H__

#define EXP_WIN_JACKPOT 20
#define EXP_WIN 10
#define EXP_LOSE 0

#define JSON_BOT_NAME "list_name"
#define JSON_BOT_AVATAR "list_avata"
#define JSON_BOT_NICK_NAME "list_nick_name"

#define MAX_BOT_MONEY 50
#define MIN_BOT_MONEY 20

#define SVR_RESULT_FAIL_JACKPOT_MINIMUM_MONEY -1

#define MATCH_COUNT_NEW_USER 50
#define MATCH_COUNT_NEW_CITY 50

#define MAX_RE_DEAL_COUNT 150

#define MATCH_COUNT_BOT_CANT_INSTANTLY_WIN 20
#define MATCH_MAXIMUM_SCORE_OF_NEW_USER 40

#define BONUS_POINTS_GIN 25
#define BONUS_POINTS_BIG_GIN 50
#define BONUS_POINTS_UNDERCUT 25

#define RATIO_BET 1

#define RESULT_DETAIL_HAND_POINTS 0
#define RESULT_DETAIL_WIN_POINTS 1
#define RESULT_DETAIL_BONUS_POINTS_GIN 2
#define RESULT_DETAIL_BONUS_POINTS_BIG_GIN 3
#define RESULT_DETAIL_BONUS_POINTS_UNDERCUT 4
#define RESULT_DETAIL_BONUS_POINTS_SPADES_DOUBLE 5
#define RESULT_DETAIL_NORMAL_WIN 6
#define RESULT_DETAIL_BONUS_WIN 7
#define RESULT_DETAIL_JACKPOT_WIN 8
#define RESULT_DETAIL_MAX_SIZE 9

#define USER_DEFAULT_NAME "You"

#endif //__INGAME_SERVER_OFFLINE_DEFINES_H__
