source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

#target 'GinOffline-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for GinOffline-desktop

#end

target 'GinOffline-mobile' do
  pod 'GoogleToolboxForMac'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
  pod 'GoogleMobileAdsMediationFacebook'
  pod 'GoogleMobileAdsMediationTestSuite'

  use_frameworks! :linkage => :static
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["DEVELOPMENT_TEAM"] = "58VAFFWBVF"
         end
    end
  end
end


# https://firebase.google.com/docs/ios/setup#available-pods
